### ISSUE TITLE
How to configure for local development

### ISSUE THREAD

**Issue by tomlancaster** [grahamar/aws-leader-election#1]
Hi @grahamar - thanks for this interesting library. I'm trying to use it for my application, but getting stuck on running it in a singular local mode. If I omit the seed nodes I get an error about min-nr-of-seeds; if I specify seed nodes my error log fills with messages indicating the cluster was not able to contact them.

What is a sensible local akka config?

Thanks for any help.

**Comment by grahamar** [comment]
Hey @tomlancaster, sorry for not getting back to you sooner, I was on holidays.

There's a bit in the README about providing `-Daws.leader.local=true` when running locally. That should sort it for you.

**Comment by ilangostl** [comment]
I am interested in trying this project. I have a couple questions.
1) what is PnP
2) can i set this up locally?
3) is the leader like a virtual server in a network. Of nodes where there is no one fixed leader?

**Comment by grahamar** [comment]
1) PnP = Plug and Play
2) Yes
I don't understand your last question. This is a library for use in multi-instance Scala/Java services where you want a single instance to become a leader, for example so you can have a background job run on only a single instance of your service.
